name: 'Purge artifacts'
description: 'Automatically delete artifacts'
branding:
  icon: 'trash-2'
  color: 'red'
author: 'Pavel Kolář'
inputs:
  expire-in:
    required: false
    description: 'Human readable expire duration'
  pattern:
    required: false
    description: 'Regular expression'
  token:
    required: true
    description: 'Github auth token'
runs:
  using: 'node12'
  main: 'dist/index.js'
